### ISSUE TITLE
:: In URL breaks Lighttpd

### ISSUE THREAD

**Issue by divineslight** [dperrymorrow/Fire-Log#14]
Hey,

Great spark, but it gives me 404 on Lighttpd, because of :: in URL.
i.e. Lightty's mod_rewrite fudges up.

If I don't use rewriting and use index.php/.... it works.

Can you please fix it?

**Comment by dperrymorrow** [comment]
you can make the param dilem whatever you would like in the config

https://github.com/dperrymorrow/Fire-Log/blob/master/config/fire_log.php

**Comment by divineslight** [comment]
That's alright thanks :)

But wouldn't it be better that you chose some safe alternative so that no one else have to see the error? 

Thanks again,
Munir

**Comment by dperrymorrow** [comment]
to be quite honest i have no idea what "Lighttpd" is and this is the first complaint i have received in over 700 installs.

**Comment by divineslight** [comment]
Alright, but Lighttpd is the most Memory effective webserver out there you use it with PHP FPM and APC to get the true grind out of your server.

Thanks for your time and good day!

**Comment by dperrymorrow** [comment]
thanks for using my spark and trying to improve it. what would be a safe param dilem symbol?
