### ISSUE TITLE
italian lang file

### ISSUE THREAD

**Issue by tudo75** [dperrymorrow/Fire-Log#15]
italian lang file
http://dl.dropbox.com/u/16264504/fire_log_lang.php

screenshots of fire_log in my app
http://dl.dropbox.com/u/16264504/fire_log.png
http://dl.dropbox.com/u/16264504/tire_log2.png

**Comment by dperrymorrow** [comment]
great thanks, can you do a pull request and ill merge it into the repo?

**Comment by tudo75** [comment]
Done

**Comment by dperrymorrow** [comment]
ok ill get that pulled in, i promise, im starting a new job this week so a
little distracted from my open source

On Sun, Jun 3, 2012 at 9:59 AM, Nicola Tudino <
reply@reply.github.com
