### ISSUE TITLE
Tried to install manually, got a PHP error.

### ISSUE THREAD

**Issue by SneakyDave** [dperrymorrow/Fire-Log#2]
For whatever reason, I can't install sparks through the CLI, but until now, I could install them manually. With fire_log, I install the extracted zip contents to my sparks directory, creating a "fire_log-0.7.0" directory.

In my controller, I load the spark with
this->load->spark('fire_log-0.7.0');

And I get this error:
A PHP Error was encountered
Severity: Warning
Message: include(.//third_party/config/fire_log.php): failed to open stream: No such file or directory
Filename: core/Config.php
Line Number: 115

I assume a file is missing that should be tin the third_party directory?

**Comment by dperrymorrow** [comment]
what version of CI are you running?

**Comment by SneakyDave** [comment]
CodeIgniter_2.0.2

**Comment by dperrymorrow** [comment]
ok ill look into it, why cant you use the CLI not working for you?

**Comment by dperrymorrow** [comment]
you very well may be experiencing this problem. 2.0.2 did not play nice with sparks 
http://codefury.net/2011/05/getsparks-org-beta-released-big-changes/

**Comment by SneakyDave** [comment]
I can use the CLI to install the spark, but for some unknown reason (I think it's SELinux-based), when I try to load any spark in a controller, I get a permissions error when it tries to read autoload.php file in MY_Loader.php. I have no idea why, even with the example-spark. The permissions can be world-writable and it will refuse the load the file.

**Comment by SneakyDave** [comment]
OK, the 2.0.2 bug caused my problem. The issue I have now is that my logs aren't in the app folder, which from what I gather, is where fire log wants them to be. 

```
Line 79   $list = get_dir_file_info( APPPATH . 'logs' );
```

So I can just overwrite those or create a symlink to the real ones. Thanks for your help

**Comment by dperrymorrow** [comment]
sure, sorry thats hardcoded, you can do a pull request and make it in the config if you like and ill implement your suggestion.
