### ISSUE TITLE
fire_log_view can't be found

### ISSUE THREAD

**Issue by SneakyDave** [dperrymorrow/Fire-Log#4]
I run nginx, and I've run into a couple of issues where I'm not sure if this is a fire_log problem or a sparks problem.

First, when I try to access my controller that loads up fire_log, I get a "no input specified" error in my browser. I traced it to the fact that fire_log tries to put he file name of the log in the URL, such as:
http://site.com/logs/file::log-2011-07-03.php

Or something similar. My web server doesn't like the .php extension in the file name, and I think fastcgi chokes on it thinking its a file request. I changed fire_log a little to not spit out the .php extension in the url, but just append it file doing the get_file. 

Anyway, I got past that, but here's the really weird part. It gets to the point of trying to load the fire_log_view, and it says it can't find it. It will load views in my main application views directory, but I don't know how it is supposed to know that fire_log_view is in the application/sparks/fire_log/0.7.0/views  directory. 

I assume this is a nginx/fastcgi configuration difference, because my apache configuration seems to work fine.

**Comment by Militis** [comment]
I recently upgraded from PHP 5.2 fastcgi to PHP 5.3 fastcgi and it fixed this problem for me. I'm using DreamHost as my host.

**Comment by dperrymorrow** [comment]
hmm, not sure on that, i may be using php 5.3 only features but not that I'm aware of

**Comment by dperrymorrow** [comment]
this is fixed in the latest version of the spark, 2.0.3 changed the way you set the loader prefix path, so i have updated to support this.
