### ISSUE TITLE
Log file's header text interfering with log display

### ISSUE THREAD

**Issue by Militis** [dperrymorrow/Fire-Log#7]
Screenshot here: http://i.imgur.com/x0T9X.png

The opening < causes the font size of the log to be larger on the first page than it is on the rest.

I've display: none;'d my log, because it had file paths and things I don't need the public to see. If you really need to see what it looks like, I can email it to you.

Also, the pagination links are off by 1 on the bottom. Any ideas why?

**Comment by dperrymorrow** [comment]
the pagination has been fixed by a pull request from split feed, i have not however re published the spark with this fix, if you want latest get it from the repo here.

Im fairly confident that you have turned off strip tags in your fire log config file, this strips out that <? tag at the beginning of each log file. thats the only way i could reproduce this error.

**Comment by Militis** [comment]
Alrighty, will do.

I wasn't 100% sure what it did, but now that I know I'll turn it back on.

Thanks a lot.

**Comment by Militis** [comment]
Sorry to reopen this, but I noticed the pagination links on the bottom were still off.

Here's a simple test: https://gist.github.com/1246476

The result is something like this:

```
 1 2 3 4 5 6 > 
Oh hai
 1 2 3 4 5 6 > 
 < 1 _2_ 3 4 5 6 > 
 < 1 2 _3_ 4 5 6 > 
 < 1 2 3 _4_ 5 6 > 
 < 1 2 3 4 _5_ 6 > 
 < 1 2 3 4 5 _6_
```

I'll send a pull request that fixes this.

**Comment by dperrymorrow** [comment]
thanks man i have pushed this version out to getsparks and made it so that it supports CI 2.0.3 whats your twitter handle ill give you a shout out for the help.

**Comment by Militis** [comment]
I'm @militis88 (real name is Mike). Thanks David, glad to be able to help with something I use every day.

Now I just wish CodeIgniter would get into using Exceptions. My debugging life would be complete. Hah.

**Comment by dperrymorrow** [comment]
well now that code igniter is on github i want to get involved been looking for tickets i can help with

**Comment by Militis** [comment]
Just an F.Y.I., the latest commit breaks in CI 2.0.2.

**Comment by dperrymorrow** [comment]
yeah unfortunately you will have to use previous versions if you are older
than 2.0.3
i was getting complaints about several of my sparks breaking in the newest
version of CI

**Comment by Militis** [comment]
Yeah, no worries. I just wanted to let you know, in case you start getting complaints from the other half. (Those pre-2.0.3, lol).

**Comment by dperrymorrow** [comment]
good point, i can add instruction in the readme, that they should install an
older version if they are not 2.0.3

**Comment by dperrymorrow** [comment]
do you know a way to get the CI version as a variable so i can switch on it and handle the view loading differently for each version of CI?

**Comment by Militis** [comment]
I do actually. On line 36 of `system/core/CodeIgniter.php`:

`define('CI_VERSION', '2.0.3');`

**Comment by dperrymorrow** [comment]
cool thanks,
im going to switch how im loading the sparks views based on the version,
then hopefully everyone can be happy :)
